dvh_fam_TS_dbt:
  target: dev
  outputs:
    dev:
      type: oracle
      protocol: "tcp"
      user: "{{env_var('DBT_ORCL_USER_PROXY')}}"
      pass: "{{env_var('DBT_ORCL_PASS')}}"
      host: "{{env_var('DBT_ORCL_HOST')}}"
      port: 1521
      service: "{{env_var('DBT_ORCL_SERVICE')}}"
      schema: "{{env_var('DBT_ORCL_SCHEMA')}}"
      threads: 7
  session_info:
    client_info: "{{env_var('DBT_ORCL_USER_PROXY', 'DVH_FAM_DBT')}}"
    module: "{{env_var('AIRFLOW_DAG_ID', 'dvh_fam_ts_dbt')}}"
    action: "Kjører utpakking av tilleggsstonad data"
