version: 2

sources:
  - name: dt_person
    schema: dt_person
    tables:
      - name: dim_person_kontaktinfo
        description: 'Inneholder informasjon om brukere, bla navn, telefon_mobil, k67_flagg osv, '
      - name: dvh_person_ident_off_id_ikke_skjermet
        description: 'Inneholder informasjon om personer som er ikke skjemet, bl.a fk_person1, off_id'
      - name: dim_person

  - name: dt_kodeverk
    schema: dt_kodeverk
    tables:
     - name: dim_alder
     - name: dim_tid
     - name: dim_kjonn
     - name: dim_geografi

  - name: fam_ef
    schema: dvh_fam_ef
    tables:
      - name: fam_ts_meta_data
        description: 'Inneholder meta_data for tilleggsstønader'
      - name: fam_ts_fagsak
        description: 'inneholder vedtaksinformasjon'
      - name: fam_ts_barn
        description: 'Inneholder informasjon om barna som kommer i vedtaket'
      - name: fam_ts_ur_utbetaling
        description: 'Inneholder utbetalinger til TS område'
      - name: fam_ts_meta_data_v2
        description: 'Inneholder meta_data for tilleggsstønader v2'
      - name: fam_ts_fagsak_v2
        description: 'inneholder vedtaksinformasjon v2'
      - name: fam_ts_vedtaksperioder_v2
      - name: fam_ts_barn_v2


